import { ActionMetadata } from "./types"

export const ACTION_METADATA: ActionMetadata[] = [
	{
		id: "readFiles",
		label: "Read project files",
		shortName: "Read",
		labelKey: "autoApprove.readFiles.label",
		shortNameKey: "autoApprove.readFiles.short",
		icon: "codicon-search",
		subAction: {
			id: "readFilesExternally",
			label: "Read all files",
			shortName: "Read (all)",
			labelKey: "autoApprove.readFilesExternally.label",
			shortNameKey: "autoApprove.readFilesExternally.short",
			icon: "codicon-folder-opened",
			parentActionId: "readFiles",
		},
	},
	{
		id: "editFiles",
		label: "Edit project files",
		shortName: "Edit",
		labelKey: "autoApprove.editFiles.label",
		shortNameKey: "autoApprove.editFiles.short",
		icon: "codicon-edit",
		subAction: {
			id: "editFilesExternally",
			label: "Edit all files",
			shortName: "Edit (all)",
			labelKey: "autoApprove.editFilesExternally.label",
			shortNameKey: "autoApprove.editFilesExternally.short",
			icon: "codicon-files",
			parentActionId: "editFiles",
		},
	},
	{
		id: "executeSafeCommands",
		label: "Execute safe commands",
		shortName: "Safe Commands",
		labelKey: "autoApprove.executeSafeCommands.label",
		shortNameKey: "autoApprove.executeSafeCommands.short",
		icon: "codicon-terminal",
		subAction: {
			id: "executeAllCommands",
			label: "Execute all commands",
			shortName: "All Commands",
			labelKey: "autoApprove.executeAllCommands.label",
			shortNameKey: "autoApprove.executeAllCommands.short",
			icon: "codicon-terminal-bash",
			parentActionId: "executeSafeCommands",
		},
	},
	{
		id: "useBrowser",
		label: "Use the browser",
		shortName: "Browser",
		labelKey: "autoApprove.useBrowser.label",
		shortNameKey: "autoApprove.useBrowser.short",
		icon: "codicon-globe",
	},
	{
		id: "useMcp",
		label: "Use MCP servers",
		shortName: "MCP",
		labelKey: "autoApprove.useMcp.label",
		shortNameKey: "autoApprove.useMcp.short",
		icon: "codicon-server",
	},
]

export const NOTIFICATIONS_SETTING: ActionMetadata = {
	id: "enableNotifications",
	label: "Enable notifications",
	shortName: "Notifications",
	labelKey: "autoApprove.notifications.label",
	shortNameKey: "autoApprove.notifications.label",
	icon: "codicon-bell",
}
